Update/readme
Yuuto-Project/yuupy pull request #16
Opened 2021-04-14 18:40 UTC by zsotroav

I have tried updating the readme.md file to better represents the current state of the project. It is far from complete, but I want everyone to take a look at it and criticize my work. 

I ran the raw text through Grammarly, but minor grammar errors are inevitable. If you find one, report it immediately.

2021-04-14 19:38 UTC, duncte123 commented
Looks good to me

2021-04-14 21:00 UTC, duncte123 approved these changes

2021-04-15 12:06 UTC, duncte123 requested changes
It's missing some docker stuff:

```markdown
### docker setup

1. Install docker and docker-compose (if not installed yet)
2. Copy `docker-compose.example.yml` to `docker-compose.override.yml` (override is ignored by git)
3. Fill in the env vars in `docker-compose.override.yml`
4. Run `docker-compose up --build` to start the bot
5. Run `docker-compose down` to stop the bot (ctrl-c works but that does not clean up the container)
```

2021-04-15 12:52 UTC, duncte123 requested changes

2021-04-15 12:52 UTC, duncte123 commented on README.md
> +YuuPy bot (formerly Yuuto or Kyuuto) is meant to be a collaboration of the [Official Camp Buddy Fan Server](https://discord.gg/campbuddy) members, completely community-driven and open source. The bot
Hiro got renamed :)
```suggestion
YuuPy bot (formerly Yuuto or Kyuuto) is meant to be a collaboration of the [Official Camp Buddy Fan Server](https://discord.gg/campbuddy) members, completely community-driven and open source. The bot's idea came from an increasing number of tech-oriented campers asking to see or contribute to _Hiro_ (the server's custom administrative bot).  
```

2021-04-15 12:52 UTC, duncte123 commented on README.md
>  ### Release branch - BabyShark
Changing up this weird flow a bit, the current one causes the branches to go out of sync
```suggestion
### Master branch - BabyShark
```

2021-04-15 12:52 UTC, duncte123 commented on README.md
> +The _release_ branch is a branch based on _develop_ branch, and any additions to it should only contain bug fixes, quality improvements, and final polishes. This branch is created once enough, or not
```suggestion
The _master_ branch is a branch based on _develop_ branch. This branch contains all code that would go into Yuuto before it releases so we have time to fix up some issues. All code in this branch is run by BabyShark.
```

2021-04-16 13:17 UTC, duncte123 approved these changes

2021-04-16 13:23 UTC, not-archiey commented
lgtm

2021-04-16 13:23 UTC, not-archiey approved these changes

2021-04-16 13:27 UTC, merged